import type { Profile, Post, Comment, Conversation, Group, Notification, Specialty, Message } from '@/types'

export const mockCurrentUser: Profile = {
  id: 'user-1',
  slug: 'ahmet-yilmaz',
  displayName: 'Dr. Ahmet Yılmaz',
  bio: 'Kardiyolog | İstanbul Üniversitesi Tıp Fakültesi | Girişimsel kardiyoloji, KAH ve kalp yetmezliği üzerine çalışmalar.',
  avatarUrl: undefined,
  accountKind: 'professional',
  isVerified: true,
  followerCount: 1842,
  followingCount: 312,
  postCount: 247,
  specialty: 'Kardiyoloji',
  institution: 'İstanbul Üniversitesi İstanbul Tıp Fakültesi',
}

export const mockProfiles: Profile[] = [
  {
    id: 'user-2',
    slug: 'elif-kaya',
    displayName: 'Dr. Elif Kaya',
    bio: 'Nörolog | Epilepsi ve MS tedavisi | Hacettepe Üniversitesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: true,
    followerCount: 2310,
    followingCount: 198,
    postCount: 184,
    specialty: 'Nöroloji',
    institution: 'Hacettepe Üniversitesi Tıp Fakültesi',
  },
  {
    id: 'user-3',
    slug: 'mehmet-ozturk',
    displayName: 'Prof. Dr. Mehmet Öztürk',
    bio: 'Onkoloji | Hematolojik maligniteler | Ankara Üniversitesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: true,
    followerCount: 5420,
    followingCount: 89,
    postCount: 412,
    specialty: 'Onkoloji',
    institution: 'Ankara Üniversitesi Tıp Fakültesi',
  },
  {
    id: 'user-4',
    slug: 'selin-arslan',
    displayName: 'Dr. Selin Arslan',
    bio: 'Pediatri uzmanı | Çocuk enfeksiyon hastalıkları | Ege Üniversitesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: false,
    followerCount: 876,
    followingCount: 445,
    postCount: 93,
    specialty: 'Pediatri',
    institution: 'Ege Üniversitesi Tıp Fakültesi',
  },
  {
    id: 'user-5',
    slug: 'ibrahim-demir',
    displayName: 'Op. Dr. İbrahim Demir',
    bio: 'Genel cerrah | Laparoskopik cerrahi | Marmara Üniversitesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: true,
    followerCount: 1204,
    followingCount: 267,
    postCount: 156,
    specialty: 'Genel Cerrahi',
    institution: 'Marmara Üniversitesi Pendik Eğitim Araştırma Hastanesi',
  },
  {
    id: 'user-6',
    slug: 'ayse-celik',
    displayName: 'Dr. Ayşe Çelik',
    bio: 'Psikiyatrist | Duygudurum bozuklukları ve anksiyete | Dokuz Eylül Üniversitesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: false,
    followerCount: 1567,
    followingCount: 334,
    postCount: 128,
    specialty: 'Psikiyatri',
    institution: 'Dokuz Eylül Üniversitesi Tıp Fakültesi',
  },
  {
    id: 'user-7',
    slug: 'can-yildiz',
    displayName: 'Dr. Can Yıldız',
    bio: 'Radyolog | Girişimsel radyoloji | Gazi Üniversitesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: true,
    followerCount: 987,
    followingCount: 156,
    postCount: 201,
    specialty: 'Radyoloji',
    institution: 'Gazi Üniversitesi Tıp Fakültesi',
  },
  {
    id: 'user-8',
    slug: 'mmc-kardiyoloji',
    displayName: 'MMC Kardiyoloji Derneği',
    bio: 'Türkiye Kardiyoloji Derneği resmi hesabı. Güncel kılavuzlar, kongreler ve haberler.',
    avatarUrl: undefined,
    accountKind: 'page',
    isVerified: true,
    followerCount: 12450,
    followingCount: 45,
    postCount: 1823,
    specialty: 'Kardiyoloji',
    institution: undefined,
  },
  {
    id: 'user-9',
    slug: 'zeynep-koc',
    displayName: 'Dr. Zeynep Koç',
    bio: 'Dermatoloji uzmanı | Kozmetik dermatoloji | İzmir Katip Çelebi Üniversitesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: false,
    followerCount: 2341,
    followingCount: 512,
    postCount: 89,
    specialty: 'Dermatoloji',
    institution: 'İzmir Katip Çelebi Üniversitesi',
  },
  {
    id: 'user-10',
    slug: 'hasan-sahin',
    displayName: 'Dr. Hasan Şahin',
    bio: 'Acil tıp uzmanı | Toksikoloji | Başakşehir Çam ve Sakura Hastanesi',
    avatarUrl: undefined,
    accountKind: 'professional',
    isVerified: false,
    followerCount: 678,
    followingCount: 289,
    postCount: 67,
    specialty: 'Acil Tıp',
    institution: 'Başakşehir Çam ve Sakura Hastanesi',
  },
]

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    author: mockCurrentUser,
    content: '<p>SGLT2 inhibitörleri artık yalnızca diyabetik hastalarda değil, kalp yetmezliği olan tüm hastalarda birinci basamak tedavi olarak önerilmektedir. EMPEROR-Reduced ve DAPA-HF çalışmaları bu yaklaşımı güçlü kanıtlarla desteklemiştir.</p><p>Özellikle HFrEF hastalarında başlangıç tedavisinde beta-bloker, ACEi/ARNi ile birlikte dapagliflozin veya empagliflozin eklendiğinde kardiyovasküler mortalite ve hospitalizasyon riski anlamlı düzeyde azalmaktadır.</p>',
    contentPlain: 'SGLT2 inhibitörleri artık yalnızca diyabetik hastalarda değil, kalp yetmezliği olan tüm hastalarda birinci basamak tedavi olarak önerilmektedir. EMPEROR-Reduced ve DAPA-HF çalışmaları bu yaklaşımı güçlü kanıtlarla desteklemiştir.\n\nÖzellikle HFrEF hastalarında başlangıç tedavisinde beta-bloker, ACEi/ARNi ile birlikte dapagliflozin veya empagliflozin eklendiğinde kardiyovasküler mortalite ve hospitalizasyon riski anlamlı düzeyde azalmaktadır.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-14T09:30:00Z',
    likeCount: 184,
    commentCount: 23,
    repostCount: 41,
    isLiked: false,
    isSaved: true,
    hasEvidence: true,
    tags: ['kardiyoloji', 'kalp_yetmezligi', 'SGLT2', 'HFrEF'],
    parentContext: {
      kind: 'group',
      slug: 'kardiyoloji-uzmanlar',
      name: 'Kardiyoloji Uzmanları Türkiye',
    },
    evidences: [
      {
        title: 'Empagliflozin in Heart Failure with a Preserved Ejection Fraction',
        sourceType: 'publication',
        identifierValue: '10.1056/NEJMoa2107038',
        url: 'https://www.nejm.org/doi/10.1056/NEJMoa2107038',
        year: 2021,
      },
      {
        title: 'Dapagliflozin in Patients with Heart Failure and Reduced Ejection Fraction',
        sourceType: 'publication',
        identifierValue: '10.1056/NEJMoa1911303',
        year: 2019,
      },
      {
        title: '2023 ESC Guidelines for Heart Failure',
        sourceType: 'clinical_guideline',
        year: 2023,
      },
    ],
  },
  {
    id: 'post-2',
    author: mockProfiles[0],
    content: '<p>Epilepsi tedavisinde yeni nesil antiepileptik ilaçlar (levetiracetam, lacosamide, brivaracetam) konvansiyonel tedavilere göre ilaç-ilaç etkileşimi profili açısından belirgin avantaj sağlamaktadır.</p><p>Özellikle politerapi gereken hastalarda CYP enzim indüksiyonu yapmayan bu ajanlar tercih edilmeli. Brivaracetam, levetiracetama kıyasla daha iyi nöropsikiyatrik profil sunuyor — bu bizim pratiğimizde önemli bir seçim kriteri haline geldi.</p>',
    contentPlain: 'Epilepsi tedavisinde yeni nesil antiepileptik ilaçlar (levetiracetam, lacosamide, brivaracetam) konvansiyonel tedavilere göre ilaç-ilaç etkileşimi profili açısından belirgin avantaj sağlamaktadır.\n\nÖzellikle politerapi gereken hastalarda CYP enzim indüksiyonu yapmayan bu ajanlar tercih edilmeli.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-14T08:15:00Z',
    likeCount: 97,
    commentCount: 14,
    repostCount: 22,
    isLiked: true,
    isSaved: false,
    hasEvidence: true,
    tags: ['nöroloji', 'epilepsi', 'antiepileptik'],
    parentContext: {
      kind: 'group',
      slug: 'noroloji-forumu',
      name: 'Nöroloji Forumu',
    },
    evidences: [
      {
        title: 'Brivaracetam vs Levetiracetam: Neuropsychiatric Adverse Events',
        sourceType: 'publication',
        identifierValue: '10.1111/epi.16725',
        year: 2021,
      },
      {
        title: 'ILAE Treatment Guidelines',
        sourceType: 'clinical_guideline',
        year: 2024,
      },
    ],
  },
  {
    id: 'post-3',
    author: mockProfiles[1],
    content: '<p>CAR-T hücre tedavisinde CRS (sitokin salınım sendromu) yönetimi kritik önem taşıyor. Tocilizumab birinci basamak tedavi olmakla birlikte, Grade 3-4 CRS vakalarında kortikosteroid kombinasyonu gerekiyor.</p><p>Anakinra ile ilgili yeni veriler umut verici — özellikle nörotoksisite ağırlıklı vakalarda steroid yerine daha iyi bir seçenek olabilir. ICANS skorlamasını rutin olarak kullanıyoruz.</p>',
    contentPlain: 'CAR-T hücre tedavisinde CRS (sitokin salınım sendromu) yönetimi kritik önem taşıyor. Tocilizumab birinci basamak tedavi olmakla birlikte, Grade 3-4 CRS vakalarında kortikosteroid kombinasyonu gerekiyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-13T16:45:00Z',
    likeCount: 256,
    commentCount: 38,
    repostCount: 67,
    isLiked: false,
    isSaved: false,
    hasEvidence: true,
    tags: ['onkoloji', 'CAR-T', 'immunoterapi'],
    evidences: [
      {
        title: 'Anakinra for CAR-T-Related Neurotoxicity',
        sourceType: 'publication',
        identifierValue: '10.1038/s41591-023-02325-4',
        year: 2023,
      },
      {
        title: 'ASTCT Consensus Grading for CRS and Neurologic Toxicity',
        sourceType: 'clinical_guideline',
        year: 2019,
      },
    ],
  },
  {
    id: 'post-4',
    author: mockProfiles[3],
    content: '<p>Laparoskopik sleeve gastrektomi sonrası nütrisyon takibi standartlaştırılmalı. Çalışmamızda 3. ayda B12, D vitamini ve demir eksikliği oranları sırasıyla %34, %28 ve %19 olarak tespit edildi.</p><p>Rutin suplementasyon protokolüne rağmen bu oranlar oldukça yüksek — hasta uyum sorununu çözmeden sadece reçete yazmak yeterli değil. Multidisipliner yaklaşım şart.</p>',
    contentPlain: 'Laparoskopik sleeve gastrektomi sonrası nütrisyon takibi standartlaştırılmalı. Çalışmamızda 3. ayda B12, D vitamini ve demir eksikliği oranları sırasıyla %34, %28 ve %19 olarak tespit edildi.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-13T14:00:00Z',
    likeCount: 143,
    commentCount: 19,
    repostCount: 31,
    isLiked: false,
    isSaved: true,
    hasEvidence: false,
    tags: ['cerrahi', 'bariatrik', 'nütrisyon'],
  },
  {
    id: 'post-5',
    author: mockProfiles[4],
    content: '<p>Majör depresif bozuklukta ketamin ve esketamin (Spravato) hızlı antidepresif etki sağlamaktadır, ancak uzun vadeli etkinlik verileri hâlâ sınırlı. İntihar riski yüksek hastalarda akut kriz döneminde kullanımı mantıklı görünüyor.</p><p>Türkiye\'de esketaminin erişilebilirliği konusunda sıkıntı yaşıyoruz — umarım geri ödeme kapsamına alınır. Deneyimlerinizi paylaşır mısınız?</p>',
    contentPlain: 'Majör depresif bozuklukta ketamin ve esketamin (Spravato) hızlı antidepresif etki sağlamaktadır, ancak uzun vadeli etkinlik verileri hâlâ sınırlı. İntihar riski yüksek hastalarda akut kriz döneminde kullanımı mantıklı görünüyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-13T11:30:00Z',
    likeCount: 201,
    commentCount: 47,
    repostCount: 53,
    isLiked: true,
    isSaved: false,
    hasEvidence: false,
    tags: ['psikiyatri', 'depresyon', 'ketamin'],
  },
  {
    id: 'post-6',
    author: mockProfiles[5],
    content: '<p>Transarteriyel radyoembolizasyon (TARE/Y90) hepatosellüler karsinomda umut verici sonuçlar vermekte. Özellikle portal ven trombozu olan hastalarda transarteriyel kemoembolizasyona (TACE) üstünlük sağlayabiliyor.</p>',
    contentPlain: 'Transarteriyel radyoembolizasyon (TARE/Y90) hepatosellüler karsinomda umut verici sonuçlar vermekte.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-13T09:00:00Z',
    likeCount: 88,
    commentCount: 11,
    repostCount: 24,
    isLiked: false,
    isSaved: false,
    hasEvidence: true,
    tags: ['radyoloji', 'girişimsel', 'HCC'],
  },
  {
    id: 'post-7',
    author: mockProfiles[7],
    content: '<p>2024 ESC Atriyal Fibrilasyon Kılavuzu\'ndaki en önemli değişiklikler: risk sınıflandırması için "4S-AF" şemasının benimsenmesi ve erken ritim kontrolünün mortalite avantajı. Özellikle EAST-AFNET 4 çalışması erken müdahaleyi destekliyor.</p><p>Avrupa verilerine göre AF prevalansı yaşlı nüfusta %10\'u aşıyor — bu bize hem inme profilaksisinde hem de ritim kontrolünde çok daha agresif davranmamız gerektiğini söylüyor.</p>',
    contentPlain: '2024 ESC Atriyal Fibrilasyon Kılavuzu\'ndaki en önemli değişiklikler: risk sınıflandırması için "4S-AF" şemasının benimsenmesi ve erken ritim kontrolünün mortalite avantajı.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-12T17:20:00Z',
    likeCount: 312,
    commentCount: 56,
    repostCount: 89,
    isLiked: false,
    isSaved: true,
    hasEvidence: true,
    tags: ['kardiyoloji', 'AF', 'ESC', 'kılavuz'],
  },
  {
    id: 'post-8',
    author: mockProfiles[2],
    content: '<p>Ekzama (atopik dermatit) tedavisinde biyolojikler devrim yarattı. Dupilumab IL-4/IL-13 yolağını bloke ederek orta-şiddetli hastalarda %75+ EASI skoru düşüşü sağlıyor.</p><p>Tralokinumab (IL-13 spesifik) ve lebrikizumab da iyi alternatifler. JAK inhibitörleri (upadacitinib, abrocitinib) ise hızlı yanıt aranan durumlarda tercih ediliyor. Ama kardiyovasküler risk faktörü olan hastalarda dikkatli olmak gerekiyor.</p>',
    contentPlain: 'Ekzama (atopik dermatit) tedavisinde biyolojikler devrim yarattı. Dupilumab IL-4/IL-13 yolağını bloke ederek orta-şiddetli hastalarda %75+ EASI skoru düşüşü sağlıyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-12T14:15:00Z',
    likeCount: 167,
    commentCount: 29,
    repostCount: 45,
    isLiked: false,
    isSaved: false,
    hasEvidence: true,
    tags: ['dermatoloji', 'atopik_dermatit', 'dupilumab'],
  },
  {
    id: 'post-9',
    author: mockProfiles[8],
    content: '<p>Acil serviste sepsis yönetimi: İlk 1 saatte antibiyotik başlanması mortaliteyi belirgin azaltıyor. Ama "saatlik antibiyotik" hedefi bazen antibiyotik aşırı kullanımına yol açabiliyor.</p><p>Prokalsitonin rehberliğinde tedavi süresi kısaltılması özellikle gram negatif sepsis için kanıtlıdır. Kültür almadan antibiyotik başlamamak da unutulmamalı — dirençli patojenleri seçip seçmiyoruz kendimize sormamız lazım.</p>',
    contentPlain: 'Acil serviste sepsis yönetimi: İlk 1 saatte antibiyotik başlanması mortaliteyi belirgin azaltıyor. Ama "saatlik antibiyotik" hedefi bazen antibiyotik aşırı kullanımına yol açabiliyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-12T10:45:00Z',
    likeCount: 234,
    commentCount: 42,
    repostCount: 61,
    isLiked: true,
    isSaved: false,
    hasEvidence: false,
    tags: ['acil_tıp', 'sepsis', 'antibiyotik'],
  },
  {
    id: 'post-10',
    author: mockCurrentUser,
    content: '<p>Koroner anjiyografi sonrası FFR (fraksiyonel akım rezervi) ölçümü rutin pratiğimize girdi. DEFER çalışmasından bu yana biliyoruz: FFR >0.80 olan lezyonlarda sadece medikal tedavi, stent kadar iyi sonuç veriyor.</p><p>iFR ve RFR gibi non-hiperemi indekslerinin kullanımı da yaygınlaşıyor. Hastalarımıza gereksiz stent yerleştirmeme adına bu araçlar kritik.</p>',
    contentPlain: 'Koroner anjiyografi sonrası FFR (fraksiyonel akım rezervi) ölçümü rutin pratiğimize girdi. DEFER çalışmasından bu yana biliyoruz: FFR >0.80 olan lezyonlarda sadece medikal tedavi, stent kadar iyi sonuç veriyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-11T15:00:00Z',
    likeCount: 148,
    commentCount: 18,
    repostCount: 37,
    isLiked: false,
    isSaved: false,
    hasEvidence: true,
    tags: ['kardiyoloji', 'FFR', 'koroner_anjiyografi'],
  },
  {
    id: 'post-11',
    author: mockProfiles[0],
    content: '<p>MS tedavisinde yüksek etkinlikli tedavilere erken geçiş stratejisi (escalation vs. early high-efficacy) tartışması devam ediyor. Ocrelizumab ve natalizumab ile elde edilen klinik remisyon oranları ilk basamak ilaçlardan belirgin şekilde üstün.</p>',
    contentPlain: 'MS tedavisinde yüksek etkinlikli tedavilere erken geçiş stratejisi (escalation vs. early high-efficacy) tartışması devam ediyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-11T11:20:00Z',
    likeCount: 119,
    commentCount: 21,
    repostCount: 29,
    isLiked: false,
    isSaved: false,
    hasEvidence: true,
    tags: ['nöroloji', 'MS', 'DMT'],
  },
  {
    id: 'post-12',
    author: mockProfiles[3],
    content: '<p>Robotiği cerrahi yaklaşım laparoskopiye kıyasla hangi durumlarda üstündür? Prostatektomi, kolorektal ve bariatrik cerrahide net avantaj mevcut. Ama genel cerrahide rutin uygulamalar için ekonomik analiz yapılmadığı sürece cevap belirsiz kalıyor.</p>',
    contentPlain: 'Robotik cerrahi yaklaşım laparoskopiye kıyasla hangi durumlarda üstündür? Prostatektomi, kolorektal ve bariatrik cerrahide net avantaj mevcut.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-10T14:30:00Z',
    likeCount: 176,
    commentCount: 33,
    repostCount: 48,
    isLiked: true,
    isSaved: true,
    hasEvidence: false,
    tags: ['cerrahi', 'robotik', 'laparoskopi'],
  },
  {
    id: 'post-13',
    author: mockProfiles[6],
    content: "<p>Yapay zeka destekli mamografi okuma (AI-aided mammography reading) ile birlikte radyolog is yukununun %30 azaldigini ve sensitivitenin arttigini gosteren calismalar sayisi giderek artiyor. Isvec'ten gelen son veriler dikkat cekici.</p><p>Radyologlarin rolu degisiyor: artik AI'nin bulmadigi ince lezyonlari yakalamak, klinik korelasyon kurmak ve hasta iletisimi bizim alanmiz. Meslektaslarim bu degisime hazir mi?</p>",
    contentPlain: 'Yapay zeka destekli mamografi okuma (AI-aided mammography reading) ile birlikte radyolog iş yükünün %30 azaldığını ve sensitivitenin arttığını gösteren çalışmalar sayısı giderek artıyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-10T09:00:00Z',
    likeCount: 289,
    commentCount: 67,
    repostCount: 92,
    isLiked: false,
    isSaved: false,
    hasEvidence: true,
    tags: ['radyoloji', 'yapay_zeka', 'mamografi'],
  },
  {
    id: 'post-14',
    author: mockProfiles[1],
    content: '<p>İmmünoterapi sonrası hipotiroidizm gelişimi çok yaygın — anti-PD1 alan hastalarda ~%10. Bazen hafif semptomlar nedeniyle atlıyor. Tiroid fonksiyon testlerini her tedavi siklusunda kontrol etmek şart.</p>',
    contentPlain: 'İmmünoterapi sonrası hipotiroidizm gelişimi çok yaygın — anti-PD1 alan hastalarda ~%10. Bazen hafif semptomlar nedeniyle atlıyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-09T16:45:00Z',
    likeCount: 134,
    commentCount: 15,
    repostCount: 28,
    isLiked: false,
    isSaved: false,
    hasEvidence: false,
    tags: ['onkoloji', 'immünoterapi', 'endokrin'],
  },
  {
    id: 'post-15',
    author: mockProfiles[4],
    content: '<p>Borderline Kişilik Bozukluğu\'nda DBT (Diyalektik Davranış Terapisi) güçlü kanıta sahip birinci basamak tedavi. Ancak ülkemizde eğitimli terapist sayısı ihtiyacı karşılamaktan çok uzak.</p><p>Türk psikiyatri camiasının bu açığı kapatmak için yapılandırılmış bir eğitim programına ihtiyacı var. Kimler DBT eğitimi veriyor — bir veritabanı oluşturabilir miyiz?</p>',
    contentPlain: 'Borderline Kişilik Bozukluğu\'nda DBT (Diyalektik Davranış Terapisi) güçlü kanıta sahip birinci basamak tedavi. Ancak ülkemizde eğitimli terapist sayısı ihtiyacı karşılamaktan çok uzak.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-09T11:00:00Z',
    likeCount: 198,
    commentCount: 44,
    repostCount: 57,
    isLiked: true,
    isSaved: true,
    hasEvidence: false,
    tags: ['psikiyatri', 'BKB', 'DBT'],
  },
  {
    id: 'post-16',
    author: mockProfiles[6],
    content: '<p>Bu hafta okuduğum bir EKG vakası: 62 yaşında erkek, ani başlangıçlı çarpıntı. Aşağıdaki trase oldukça öğretici — özellikle dal bloğu paterni ve voltaj kriterleri açısından.</p>',
    contentPlain: 'Bu hafta okuduğum bir EKG vakası: 62 yaşında erkek, ani başlangıçlı çarpıntı. Aşağıdaki trase oldukça öğretici — özellikle dal bloğu paterni ve voltaj kriterleri açısından.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-15T13:30:00Z',
    likeCount: 312,
    commentCount: 58,
    repostCount: 41,
    isLiked: false,
    isSaved: true,
    hasEvidence: false,
    tags: ['kardiyoloji', 'EKG', 'vaka'],
    media: [
      {
        id: 'media-16-1',
        url: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=1200&q=80',
        mimeType: 'image/jpeg',
        altText: 'EKG kağıdı, 12 derivasyon',
        width: 1200,
        height: 800,
      },
    ],
  },
  {
    id: 'post-17',
    author: mockProfiles[1],
    content: '<p>Tıbbi onkoloji laboratuvarımızdan birkaç kesit. Histopatolojik incelemede H&E ve immünohistokimya kombinasyonu tanı için kritik.</p>',
    contentPlain: 'Tıbbi onkoloji laboratuvarımızdan birkaç kesit. Histopatolojik incelemede H&E ve immünohistokimya kombinasyonu tanı için kritik.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-15T12:00:00Z',
    likeCount: 245,
    commentCount: 33,
    repostCount: 28,
    isLiked: true,
    isSaved: false,
    hasEvidence: false,
    tags: ['patoloji', 'onkoloji', 'histopatoloji'],
    media: [
      {
        id: 'media-17-1',
        url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Histopatoloji preparatı',
        width: 900,
        height: 900,
      },
      {
        id: 'media-17-2',
        url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Mikroskop altında doku örneği',
        width: 900,
        height: 900,
      },
    ],
  },
  {
    id: 'post-18',
    author: mockProfiles[5],
    content: '<p>BT eğitim arşivimden seçtiğim üç ilginç olgu — pulmoner emboli, hepatik metastaz ve renal kitle. Klinik bağlam ile değerlendirilmesi gereken bulgular.</p>',
    contentPlain: 'BT eğitim arşivimden seçtiğim üç ilginç olgu — pulmoner emboli, hepatik metastaz ve renal kitle. Klinik bağlam ile değerlendirilmesi gereken bulgular.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-15T11:00:00Z',
    likeCount: 187,
    commentCount: 24,
    repostCount: 19,
    isLiked: false,
    isSaved: true,
    hasEvidence: false,
    tags: ['radyoloji', 'BT', 'olgu_sunumu'],
    media: [
      {
        id: 'media-18-1',
        url: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'BT kesiti',
        width: 900,
        height: 900,
      },
      {
        id: 'media-18-2',
        url: 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Aksiyel BT',
        width: 900,
        height: 900,
      },
      {
        id: 'media-18-3',
        url: 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Kontrastlı BT',
        width: 900,
        height: 900,
      },
    ],
  },
  {
    id: 'post-19',
    author: mockProfiles[0],
    content: '<p>Yeni NEJM yayını çıktı. SGLT2 inhibitörlerinin kalp yetmezliği dışındaki endikasyonlarda da etkili olabileceğini gösteriyor — özellikle CKD ve MASH için umut verici.</p>',
    contentPlain: 'Yeni NEJM yayını çıktı. SGLT2 inhibitörlerinin kalp yetmezliği dışındaki endikasyonlarda da etkili olabileceğini gösteriyor — özellikle CKD ve MASH için umut verici.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-15T10:00:00Z',
    likeCount: 421,
    commentCount: 67,
    repostCount: 124,
    isLiked: true,
    isSaved: true,
    hasEvidence: true,
    tags: ['nefroloji', 'SGLT2', 'NEJM', 'yayın'],
    linkPreview: {
      url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2024816',
      title: 'Dapagliflozin in Patients with Chronic Kidney Disease',
      description:
        'The DAPA-CKD trial showed that dapagliflozin reduces the risk of a sustained decline in eGFR, ESRD, and death from renal or cardiovascular causes in patients with CKD with or without type 2 diabetes.',
      imageUrl:
        'https://images.unsplash.com/photo-1583912267550-d6c2ac3196c0?auto=format&fit=crop&w=400&q=80',
      siteName: 'NEJM',
    },
    evidences: [
      {
        title: 'Dapagliflozin in Patients with Chronic Kidney Disease',
        sourceType: 'publication',
        identifierValue: '10.1056/NEJMoa2024816',
        url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2024816',
        year: 2020,
      },
      {
        title: 'EMPA-KIDNEY: Empagliflozin in Patients with CKD',
        sourceType: 'publication',
        identifierValue: '10.1056/NEJMoa2204233',
        year: 2023,
      },
      {
        title: 'KDIGO 2024 Clinical Practice Guideline for Diabetes Management in CKD',
        sourceType: 'clinical_guideline',
        year: 2024,
      },
    ],
  },
  {
    id: 'post-26',
    author: mockProfiles[0],
    content: '<p>Kardiyoloji Derneği grup içi anketimiz: Periferik damar hastalığı tedavisinde anti-trombotik tercihiniz nedir? Tartışmaya katılın.</p>',
    contentPlain: 'Kardiyoloji Derneği grup içi anketimiz: Periferik damar hastalığı tedavisinde anti-trombotik tercihiniz nedir? Tartışmaya katılın.',
    postType: 'standard',
    visibility: 'group',
    createdAt: '2026-06-15T15:30:00Z',
    likeCount: 88,
    commentCount: 31,
    repostCount: 7,
    isLiked: false,
    isSaved: false,
    hasEvidence: false,
    tags: ['kardiyoloji', 'PAD', 'antikoagülan'],
    parentContext: {
      kind: 'group',
      slug: 'kardiyoloji-uzmanlar',
      name: 'Kardiyoloji Uzmanları Türkiye',
    },
  },
  {
    id: 'post-27',
    author: mockProfiles[6],
    content: '<p>Resmi sayfamızdan duyuru: 2026 Kardiyoloji Kongresi kayıtları başladı. Erken kayıt indirimi 1 Ağustos\'a kadar geçerli.</p>',
    contentPlain: 'Resmi sayfamızdan duyuru: 2026 Kardiyoloji Kongresi kayıtları başladı. Erken kayıt indirimi 1 Ağustos\'a kadar geçerli.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-15T14:45:00Z',
    likeCount: 234,
    commentCount: 18,
    repostCount: 52,
    isLiked: true,
    isSaved: true,
    hasEvidence: false,
    tags: ['kongre', 'kardiyoloji'],
    parentContext: {
      kind: 'page',
      slug: 'mmc-kardiyoloji',
      name: 'MMC Kardiyoloji Derneği',
    },
  },
  {
    id: 'post-20',
    author: mockProfiles[2],
    content: '<p>Sleeve gastrektomi sonrası mikronutrient takip rehberini güncelledik. Aşağıdaki PDF dosyasında dozaj tablosu ve kontrol aralıkları yer alıyor — kliniğinizde rahatlıkla kullanabilirsiniz.</p>',
    contentPlain: 'Sleeve gastrektomi sonrası mikronutrient takip rehberini güncelledik. Aşağıdaki PDF dosyasında dozaj tablosu ve kontrol aralıkları yer alıyor.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-15T09:00:00Z',
    likeCount: 156,
    commentCount: 22,
    repostCount: 34,
    isLiked: false,
    isSaved: true,
    hasEvidence: false,
    tags: ['cerrahi', 'bariatrik', 'rehber'],
    attachments: [
      {
        id: 'att-20-1',
        url: '#',
        originalName: 'sleeve-gastrektomi-mikronutrient-rehberi-2026.pdf',
        mimeType: 'application/pdf',
        fileSize: 2_482_173,
      },
      {
        id: 'att-20-2',
        url: '#',
        originalName: 'takip-formu-sablonu.xlsx',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        fileSize: 184_320,
      },
    ],
  },
  {
    id: 'post-21',
    author: mockCurrentUser,
    content: '<p>Bu çalışma gerçekten önemli bir noktaya değiniyor. Klinik pratiğimize hızla yansıtmamız gerekiyor.</p>',
    contentPlain: 'Bu çalışma gerçekten önemli bir noktaya değiniyor. Klinik pratiğimize hızla yansıtmamız gerekiyor.',
    postType: 'quote',
    visibility: 'public',
    createdAt: '2026-06-15T08:00:00Z',
    likeCount: 89,
    commentCount: 11,
    repostCount: 14,
    isLiked: false,
    isSaved: false,
    hasEvidence: false,
    tags: ['kardiyoloji', 'SGLT2'],
    quotedPost: {
      id: 'post-19',
      author: mockProfiles[0],
      contentPlain:
        'Yeni NEJM yayını çıktı. SGLT2 inhibitörlerinin kalp yetmezliği dışındaki endikasyonlarda da etkili olabileceğini gösteriyor — özellikle CKD ve MASH için umut verici.',
      createdAt: '2026-06-07T19:20:00Z',
    },
  },
  {
    id: 'post-22',
    author: mockProfiles[4],
    content: '<p>Yeni klinik gözlemlerimi sizinle paylaşmak istedim. Renkli arkaplan denemesi 🎨</p>',
    contentPlain: 'Yeni klinik gözlemlerimi sizinle paylaşmak istedim. Renkli arkaplan denemesi 🎨',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-15T07:00:00Z',
    likeCount: 64,
    commentCount: 8,
    repostCount: 5,
    isLiked: false,
    isSaved: false,
    hasEvidence: false,
    tags: ['paylaşım'],
    composerBg: 'lavender',
  },
  {
    id: 'post-23',
    author: mockProfiles[3],
    content: '<p>Geçen hafta bariatrik cerrahi kongresinde aldığım 4 kesit. Her birinde önemli teknik detaylar var — sleeve ve gastric bypass için.</p>',
    contentPlain: 'Geçen hafta bariatrik cerrahi kongresinde aldığım 4 kesit. Her birinde önemli teknik detaylar var — sleeve ve gastric bypass için.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-14T22:00:00Z',
    likeCount: 278,
    commentCount: 42,
    repostCount: 38,
    isLiked: true,
    isSaved: false,
    hasEvidence: false,
    tags: ['cerrahi', 'kongre', 'bariatrik'],
    media: [
      {
        id: 'media-23-1',
        url: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Cerrahi ekibi',
        width: 900,
        height: 900,
      },
      {
        id: 'media-23-2',
        url: 'https://images.unsplash.com/photo-1631815587646-b85a1bb027e1?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Cerrahi enstrümanlar',
        width: 900,
        height: 900,
      },
      {
        id: 'media-23-3',
        url: 'https://images.unsplash.com/photo-1581595219315-a187dd40c322?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Ameliyathane',
        width: 900,
        height: 900,
      },
      {
        id: 'media-23-4',
        url: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&w=900&q=80',
        mimeType: 'image/jpeg',
        altText: 'Laparoskopik görüntü',
        width: 900,
        height: 900,
      },
    ],
  },
  {
    id: 'post-24',
    author: mockProfiles[1],
    content: '<p>2026 ESMO Annual Meeting kayıtları açıldı. Erken kayıtta önemli indirim var. İlgilenenler için bağlantı aşağıda.</p>',
    contentPlain: '2026 ESMO Annual Meeting kayıtları açıldı. Erken kayıtta önemli indirim var.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-14T20:00:00Z',
    likeCount: 142,
    commentCount: 19,
    repostCount: 47,
    isLiked: false,
    isSaved: false,
    hasEvidence: false,
    tags: ['onkoloji', 'kongre', 'ESMO'],
    linkPreview: {
      url: 'https://www.esmo.org/meetings/esmo-congress-2026',
      title: 'ESMO Congress 2026 — Madrid',
      description:
        '17–21 October 2026. Join leading oncologists at the most comprehensive multidisciplinary cancer congress in Europe.',
      imageUrl: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=400&q=80',
      siteName: 'ESMO',
    },
  },
  {
    id: 'post-25',
    author: mockProfiles[7],
    content: '<p>Sleeve gastrektomi sonrası 6 ay takipte değişen bir hasta. Sadece kilo değil — komorbiditelerde de dramatik düzelme.</p>',
    contentPlain: 'Sleeve gastrektomi sonrası 6 ay takipte değişen bir hasta. Sadece kilo değil — komorbiditelerde de dramatik düzelme.',
    postType: 'standard',
    visibility: 'public',
    createdAt: '2026-06-14T18:00:00Z',
    likeCount: 198,
    commentCount: 28,
    repostCount: 22,
    isLiked: false,
    isSaved: false,
    hasEvidence: false,
    tags: ['dermatoloji', 'klinik'],
    media: [
      {
        id: 'media-25-1',
        url: 'https://cdn.coverr.co/videos/coverr-doctor-in-the-hallway-of-a-hospital-1080p.mp4',
        mimeType: 'video/mp4',
        altText: 'Klinik video — hastane koridoru',
        width: 1920,
        height: 1080,
      },
    ],
  },
]

export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    author: mockProfiles[0],
    content: 'Çok değerli bir paylaşım. Bizim kliniğimizde de benzer sonuçlar gözlemliyoruz. EF %35 altı hastalarda SGLT2i\'yi rutin hale getirdik.',
    createdAt: '2026-06-14T10:00:00Z',
    likeCount: 12,
  },
  {
    id: 'comment-2',
    author: mockProfiles[1],
    content: 'DAPA-HF ve EMPEROR-Preserved çalışmaları da HFpEF için umut verici sonuçlar gösterdi. Artık tüm EF gruplarında kullanımı tartışılıyor.',
    createdAt: '2026-06-14T10:45:00Z',
    likeCount: 8,
  },
  {
    id: 'comment-3',
    author: mockProfiles[3],
    content: 'Peki renal fonksiyonu bozuk hastalarda eGFR kesim değerini nasıl belirliyorsunuz? Kılavuzlar 20 ml/dk diyor ama pratikte daha temkinli davranıyoruz.',
    createdAt: '2026-06-14T11:30:00Z',
    likeCount: 5,
  },
  {
    id: 'comment-4',
    author: mockCurrentUser,
    content: 'Harika soru. Bizde eGFR 25 ml/dk altına düşünce idrar söktürücü etkisi için kullanmıyoruz ama kardiyoprotektif etki için devam ediyoruz. Tabii bireysel değerlendirme şart.',
    createdAt: '2026-06-14T12:00:00Z',
    likeCount: 15,
  },
  {
    id: 'comment-5',
    author: mockProfiles[5],
    content: 'Radyoloji perspektifinden de ekleyeyim: Kardiyak MR ile tedavi yanıtı değerlendirmek giderek yaygınlaşıyor. ECV fraksiyonu fibroz takibinde kullanışlı bir parametre.',
    createdAt: '2026-06-14T13:00:00Z',
    likeCount: 9,
  },
]

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participant: mockProfiles[0],
    lastMessage: {
      id: 'msg-10',
      senderId: 'user-2',
      content: 'Yarınki kongreye gelecek misiniz? Sizinle konuşmak istiyordum.',
      createdAt: '2026-06-14T14:30:00Z',
      isRead: false,
    },
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    participant: mockProfiles[1],
    lastMessage: {
      id: 'msg-20',
      senderId: 'user-1',
      content: 'Makale taslağını gönderdim, inceleme fırsatınız olursa memnun olurum.',
      createdAt: '2026-06-13T18:00:00Z',
      isRead: true,
    },
    unreadCount: 0,
  },
  {
    id: 'conv-3',
    participant: mockProfiles[2],
    lastMessage: {
      id: 'msg-30',
      senderId: 'user-3',
      content: 'Hasta konsültasyonu için teşekkürler, çok faydalı oldu.',
      createdAt: '2026-06-13T10:15:00Z',
      isRead: true,
    },
    unreadCount: 0,
  },
  {
    id: 'conv-4',
    participant: mockProfiles[7],
    lastMessage: {
      id: 'msg-40',
      senderId: 'user-8',
      content: 'Kongre bildirisi başvuru tarihi uzatıldı, lütfen paylaşın.',
      createdAt: '2026-06-12T09:00:00Z',
      isRead: false,
    },
    unreadCount: 1,
  },
  {
    id: 'conv-5',
    participant: mockProfiles[4],
    lastMessage: {
      id: 'msg-50',
      senderId: 'user-1',
      content: 'DBT eğitimi ile ilgili konuşmak isterim, müsait misiniz?',
      createdAt: '2026-06-11T16:45:00Z',
      isRead: true,
    },
    unreadCount: 0,
  },
]

export const mockMessagesByConversation: Record<string, Message[]> = {
  'conv-1': [
    { id: 'msg-1-1', senderId: 'user-1', content: 'Merhaba Dr. Kaya, EMPEROR-Reduced çalışmasını okudum, çok aydınlatıcıydı.', createdAt: '2026-06-14T09:00:00Z', isRead: true },
    { id: 'msg-1-2', senderId: 'user-2', content: 'Evet, gerçekten çok önemli bir çalışma. Nöroloji perspektifinden de kardiyovasküler risk yönetimi çok kritik.', createdAt: '2026-06-14T09:15:00Z', isRead: true },
    { id: 'msg-1-3', senderId: 'user-1', content: 'Multidisipliner yaklaşım şart. Bir vaka sunumunu birlikte yapmayı düşünüyor muydunuz?', createdAt: '2026-06-14T09:30:00Z', isRead: true },
    { id: 'msg-1-4', senderId: 'user-2', content: 'Fikir güzel! Yarınki kongreye gelecek misiniz? Sizinle konuşmak istiyordum.', createdAt: '2026-06-14T14:30:00Z', isRead: false },
    { id: 'msg-1-5', senderId: 'user-2', content: 'Kongre programını gönderdim, belki ortak bir panel yapabiliriz.', createdAt: '2026-06-14T14:35:00Z', isRead: false },
  ],
}

export const mockGroups: Group[] = [
  {
    id: 'group-1',
    slug: 'kardiyoloji-uzmanlar',
    name: 'Kardiyoloji Uzmanları Türkiye',
    description: 'Kardiyoloji alanındaki güncel araştırmalar, vaka tartışmaları ve klinik kılavuzlar için Türkiye\'nin önde gelen kardiyoloji topluluğu.',
    memberCount: 4821,
    postCount: 12540,
    specialty: 'Kardiyoloji',
    joinPolicy: 'request',
    isMember: true,
  },
  {
    id: 'group-2',
    slug: 'noroloji-forumu',
    name: 'Nöroloji Forumu',
    description: 'MS, epilepsi, inme ve nörodejeneratif hastalıklar üzerine vaka paylaşımları ve tartışmalar.',
    memberCount: 2315,
    postCount: 6782,
    specialty: 'Nöroloji',
    joinPolicy: 'open',
    isMember: true,
  },
  {
    id: 'group-3',
    slug: 'genel-cerrahi-dernegi',
    name: 'Genel Cerrahi Derneği',
    description: 'Laparoskopik, robotik ve açık cerrahi teknikler, komplikasyon yönetimi ve kanıta dayalı cerrahi pratikler.',
    memberCount: 1876,
    postCount: 5421,
    specialty: 'Genel Cerrahi',
    joinPolicy: 'request',
    isMember: false,
  },
  {
    id: 'group-4',
    slug: 'onkoloji-hematologi',
    name: 'Onkoloji & Hematoloji',
    description: 'Solid tümörler, hematolojik maligniteler, immünoterapi ve hedefli tedaviler üzerine güncel paylaşımlar.',
    memberCount: 3102,
    postCount: 9876,
    specialty: 'Onkoloji',
    joinPolicy: 'open',
    isMember: false,
  },
  {
    id: 'group-5',
    slug: 'psikiyatri-dernegi',
    name: 'Psikiyatri Derneği',
    description: 'Ruh sağlığı, psikofarmakoloji ve psikoterapi alanındaki güncel gelişmeler ve vaka tartışmaları.',
    memberCount: 1543,
    postCount: 4231,
    specialty: 'Psikiyatri',
    joinPolicy: 'open',
    isMember: true,
  },
  {
    id: 'group-6',
    slug: 'acil-tıp-grubu',
    name: 'Acil Tıp Topluluğu',
    description: 'Acil serviste karşılaşılan vakalar, protokoller ve hızlı değerlendirme teknikleri.',
    memberCount: 2891,
    postCount: 7654,
    specialty: 'Acil Tıp',
    joinPolicy: 'open',
    isMember: false,
  },
  {
    id: 'group-7',
    slug: 'radyoloji-ai',
    name: 'Radyoloji & Yapay Zeka',
    description: 'Medikal görüntülemede yapay zeka uygulamaları, deep learning ve tanısal radyoloji inovasyonları.',
    memberCount: 1234,
    postCount: 3456,
    specialty: 'Radyoloji',
    joinPolicy: 'invite_only',
    isMember: false,
  },
  {
    id: 'group-8',
    slug: 'tip-egitimi',
    name: 'Tıp Eğitimi & Akademi',
    description: 'Tıp eğitimi, simülasyon, akademik yayıncılık ve tıp öğrencileri ile asistanları için mentorluk programları.',
    memberCount: 5678,
    postCount: 15432,
    specialty: undefined,
    joinPolicy: 'open',
    isMember: false,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'like',
    actor: mockProfiles[0],
    entityType: 'post',
    entityId: 'post-1',
    createdAt: '2026-06-14T10:30:00Z',
    isRead: false,
    title: 'Dr. Elif Kaya gönderinizi beğendi',
    body: 'SGLT2 inhibitörleri artık yalnızca diyabetik hastalarda değil...',
  },
  {
    id: 'notif-2',
    type: 'comment',
    actor: mockProfiles[1],
    entityType: 'post',
    entityId: 'post-1',
    createdAt: '2026-06-14T10:45:00Z',
    isRead: false,
    title: 'Prof. Dr. Mehmet Öztürk gönderinize yorum yaptı',
    body: 'DAPA-HF ve EMPEROR-Preserved çalışmaları da HFpEF için umut verici...',
  },
  {
    id: 'notif-3',
    type: 'follow',
    actor: mockProfiles[2],
    entityType: 'post',
    entityId: '',
    createdAt: '2026-06-14T09:00:00Z',
    isRead: false,
    title: 'Dr. Selin Arslan sizi takip etmeye başladı',
  },
  {
    id: 'notif-4',
    type: 'repost',
    actor: mockProfiles[7],
    entityType: 'post',
    entityId: 'post-10',
    createdAt: '2026-06-13T16:00:00Z',
    isRead: true,
    title: 'MMC Kardiyoloji Derneği gönderinizi paylaştı',
  },
  {
    id: 'notif-5',
    type: 'mention',
    actor: mockProfiles[3],
    entityType: 'post',
    entityId: 'post-4',
    createdAt: '2026-06-13T14:15:00Z',
    isRead: true,
    title: 'Op. Dr. İbrahim Demir sizi bir gönderide etiketledi',
    body: '@ahmet-yilmaz Kardiyoloji açısından ne düşünürsünüz?',
  },
  {
    id: 'notif-6',
    type: 'like',
    actor: mockProfiles[4],
    entityType: 'post',
    entityId: 'post-7',
    createdAt: '2026-06-13T11:00:00Z',
    isRead: true,
    title: 'Dr. Ayşe Çelik gönderinizi beğendi',
  },
  {
    id: 'notif-7',
    type: 'comment',
    actor: mockProfiles[5],
    entityType: 'post',
    entityId: 'post-1',
    createdAt: '2026-06-13T10:00:00Z',
    isRead: true,
    title: 'Dr. Can Yıldız gönderinize yorum yaptı',
    body: 'Kardiyak MR ile tedavi yanıtı değerlendirmek giderek yaygınlaşıyor...',
  },
  {
    id: 'notif-8',
    type: 'follow',
    actor: mockProfiles[6],
    entityType: 'post',
    entityId: '',
    createdAt: '2026-06-12T15:30:00Z',
    isRead: true,
    title: 'Dr. Zeynep Koç sizi takip etmeye başladı',
  },
  {
    id: 'notif-9',
    type: 'like',
    actor: mockProfiles[8],
    entityType: 'post',
    entityId: 'post-10',
    createdAt: '2026-06-12T09:45:00Z',
    isRead: true,
    title: 'Dr. Hasan Şahin gönderinizi beğendi',
  },
  {
    id: 'notif-10',
    type: 'repost',
    actor: mockProfiles[0],
    entityType: 'post',
    entityId: 'post-7',
    createdAt: '2026-06-11T17:00:00Z',
    isRead: true,
    title: 'Dr. Elif Kaya gönderinizi paylaştı',
  },
]

export const mockSpecialties: Specialty[] = [
  { id: 'spec-1', name: 'Kardiyoloji', slug: 'kardiyoloji', icon: '❤️' },
  { id: 'spec-2', name: 'Nöroloji', slug: 'noroloji', icon: '🧠' },
  { id: 'spec-3', name: 'Onkoloji', slug: 'onkoloji', icon: '🔬' },
  { id: 'spec-4', name: 'Pediatri', slug: 'pediatri', icon: '👶' },
  { id: 'spec-5', name: 'Genel Cerrahi', slug: 'genel-cerrahi', icon: '🏥' },
  { id: 'spec-6', name: 'Psikiyatri', slug: 'psikiyatri', icon: '🧘' },
  { id: 'spec-7', name: 'Ortopedi', slug: 'ortopedi', icon: '🦴' },
  { id: 'spec-8', name: 'Dahiliye', slug: 'dahiliye', icon: '💊' },
  { id: 'spec-9', name: 'Radyoloji', slug: 'radyoloji', icon: '📡' },
  { id: 'spec-10', name: 'Anesteziyoloji', slug: 'anestezi', icon: '💉' },
  { id: 'spec-11', name: 'Göz Hastalıkları', slug: 'goz-hastaliklari', icon: '👁️' },
  { id: 'spec-12', name: 'KBB', slug: 'kbb', icon: '👂' },
  { id: 'spec-13', name: 'Dermatoloji', slug: 'dermatoloji', icon: '🌿' },
  { id: 'spec-14', name: 'Üroloji', slug: 'uroloji', icon: '🫘' },
  { id: 'spec-15', name: 'Gastroenteroloji', slug: 'gastroenteroloji', icon: '🔄' },
  { id: 'spec-16', name: 'Kadın Hastalıkları', slug: 'kadin-hastaliklari', icon: '🌸' },
  { id: 'spec-17', name: 'Acil Tıp', slug: 'acil-tip', icon: '🚑' },
  { id: 'spec-18', name: 'Aile Hekimliği', slug: 'aile-hekimligi', icon: '🏡' },
  { id: 'spec-19', name: 'Patoloji', slug: 'patoloji', icon: '🔭' },
  { id: 'spec-20', name: 'Fizyoterapi', slug: 'fizyoterapi', icon: '🏃' },
]
